### ISSUE TITLE
Drop Python 3.6

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/openff-toolkit-feedstock#11]
It didn't make it into the release notes, but we agreed that the 0.9.1. release would be the last one supporting Python 3.6. We should consider upgrading the pins in the feedstock to avoid users incidentally installing newer toolkit versions with Python 3.6, which we do not test on.

**Comment by j-wags** [comment]
I'm actually in favor of keeping it until something breaks. It's not the best devops practice, but 3.6 is still widely-used enough that I don't want to forbid it until we have to.

**Comment by mattwthompson** [comment]
I'd be okay with that strategy on the condition that we go back to testing it as well. Should breakage be the criteria for dropping support, it's going to happen, and I'd rather it happen in our automation than on a user's computer.

I figure we would only need to turn them back on for deployment tests, not full CI/examples/etc. matrix.

https://github.com/openforcefield/openff-toolkit/blob/8248f5ae667ebfa0009b6bb96d36bf46059b9140/.github/workflows/conda.yml#L22-L37

**Comment by j-wags** [comment]
Done :-)

**Comment by mattwthompson** [comment]
Great, thanks!
