### ISSUE TITLE
Constrain to AT22 or newer

### ISSUE THREAD

**Issue by j-wags** [conda-forge/openff-toolkit-feedstock#48]
Can we a least constrain to 22 or newer? 20 allows ParmEd 4 to be brought in, which breaks examples

_Originally posted by @mattwthompson in https://github.com/conda-forge/openff-toolkit-feedstock/pull/46#discussion_r1178253378_

**Comment by jaimergp** [comment]
Consider using [`conda-forge-repodata-paches-feedstock`](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) to amend the repodata (mostly version pins in your deps) in existing packages.

**Comment by j-wags** [comment]
Woooooaaaah. That's really nifty - Thanks for pointing it out @jaimergp. Is there a preference from the c-f side between us making new builds to add pins vs. modifying them in existing pacakges? I'd think that modifying an already-released package should only be done in emergencies.

**Comment by mattwthompson** [comment]
IIUC patching is strictly the better option in terms of the infrastructure but it requires somebody to review & merge it

**Comment by jaimergp** [comment]
The problem is that you are leaving older versions "exposed" to too optimistic version constraints, so the solver might go and choose that solution. If you see that you are getting really old ambertools / openff versions when you do a simple `conda install openff`, that might be the explanation.

**Comment by mattwthompson** [comment]
Done 66316ae; can patch the existing repodata if this is reported by users
