### ISSUE TITLE
Downpin against new major versions of upstreams?

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/openff-toolkit-feedstock#85]
### Comment:

While I was looking at https://github.com/conda-forge/openff-toolkit-feedstock/pull/84 I wondered if it'd be worth it to add `ambertools <24` since it's not out yet and it runs a (tiny) chance of breaking something.

If we got into the habit of constraining to current major or minor versions of important upstreams, it'd had the benefit of new releases being less likely to break things. There would be the downside of a little more work in testing new versions before loosening constraints

**Comment by j-wags** [comment]
Not a bad idea, but overall I'm slightly in favor of "be permissive and panic when something breaks" over "be conservative and remember to update pins". My preference is wholly because I can't remember anything for more than 3 seconds, so if I downpin something I'll forget about it immediately and leave cruft in our metadata.

**Comment by mattwthompson** [comment]
That's fair; I think this makes sense for larger upstreams which are more likely to cause us surprises and/or have a history of making breaking changes that break downstreams. I think any of these downpins should come with a paper trail, too

**Comment by j-wags** [comment]
That's true, but overall I'm still not in favor. 

Thinking a bit more, I think that having the alarm bells go off immediately is actually a pretty major feature. Just last week we were the first to catch broken builds of RDKit and OpenEye (despite these packages being available to the entire world for several days). This indicates to me that 1) we're the correct mixture of vigilant and loud that we're effectively the first responders for the ecosystem and 2) having the alarm go off quickly reduces possible confounders, and maintainers are more likely to take reports seriously if we inform them shortly after they've made a bad release/build. 

I guess we COULD have separate pins for dev testing and conda packages but... this goes back to the "memory of a goldfish" issue. Overall I'm in favor of the status quo.
